export const SET_CHARACTERS = "SET_CHARACTERS";
export const SET_NEXT_PAGE_CHARACTERS = "SET_NEXT_PAGE_CHARACTERS";
export const SET_CHARACTER_BY_ID = "SET_CHARACTER_BY_ID";
export const RESET = "RESET";
export const LOADING = "LOADING";
export const SET_TOAST_ERROR_MESSAGE = "SET_TOAST_ERROR_MESSAGE";
