import Head from "next/head";
import axios from "axios";
import PullToRefresh from "../components/PullToRefresh";
import Character from "../components/Character";
import styles from "../styles/Home.module.css";
import Button from "@mui/material/Button";
import Link from "next/link";
import { useSelector, useDispatch } from "react-redux";
import { getCharacters, resetCharacters } from "../store/actions";

export default function Home() {
  const characterResults = useSelector((state) => state.data);
  const dispatch = useDispatch();

  const handleClick = () => {
    dispatch(resetCharacters());
  };

  const handleRefresh = () => {
    dispatch(getCharacters(axios));
  };

  const characters = characterResults.characters ?? [];

  return (
    <div className={styles.container}>
      <Head>
        <title>Obe fitness takehome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Button onClick={handleClick} variant="contained">
          Reset
        </Button>
        <PullToRefresh
          onRefresh={handleRefresh}
          loading={characterResults.loading}
        >
          {characters.map((character, index) => {
            const link = index + 1;
            return (
              <Link key={index} href={"character/" + link.toString()}>
                <Character data={character}></Character>
              </Link>
            );
          })}
        </PullToRefresh>
      </main>
    </div>
  );
}
