import Head from "next/head";
import { useState, useEffect } from "react";
import axios from "axios";
import PullToRefresh from "../components/PullToRefresh";
import Character from "../components/Character";
import styles from "../styles/Home.module.css";
import Button from "@mui/material/Button";
import Link from "next/link";
import { useSelector, useDispatch } from "react-redux";
import {
  getCharacters,
  getNextPageCharacters,
  resetCharacters,
} from "../store/actions";

export default function Home() {
  const characterResults = useSelector((state) => state.data);
  const dispatch = useDispatch();

  const handleClick = () => {
    dispatch(resetCharacters());
  };

  const handleRefresh = () => {
    dispatch(getCharacters(axios));
  };

  useEffect(() => {
    const handleScroll = (event) => {
      if (
        window.innerHeight + window.pageYOffset >=
        document.body.offsetHeight
      ) {
        dispatch(getNextPageCharacters(axios));
        window.scrollTo(0, 0);
      }
    };

    window.addEventListener("scroll", handleScroll);

    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  const characters = characterResults.characters ?? [];

  return (
    <div className={styles.container}>
      <Head>
        <title>Obe fitness takehome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Button onClick={handleClick} variant="contained">
          Reset
        </Button>
        <div id="test" className={styles.resultsContainer}>
          <PullToRefresh
            onRefresh={handleRefresh}
            loading={characterResults.loading}
          >
            {characters.map((character, index) => {
              const link = character.id;
              return (
                <Link key={index} href={"character/" + link.toString()}>
                  <Character data={character}></Character>
                </Link>
              );
            })}
          </PullToRefresh>
        </div>
      </main>
    </div>
  );
}
